### ISSUE TITLE
Restarting lol miner.

### ISSUE THREAD

**Issue by sheminasalam** [bds89/miner2mqtt#2]
Is there any way by which lolminer can be restarted with this?

**Comment by bds89** [comment]
No, there is no such possibility now.  I had thoughts of adding this when I was using lol-miner 1.43 and it kept crashing in dual mining, but version 1.50 works fine, at least on eth+ton algorithms.  I will still see if I can add the ability to restart the miner from the code.  The miner started with sudo, so you can only terminate such a process from a process running with sudo. I'll see if I can somehow get around this so as not to start the m2m process with sudo

**Comment by sheminasalam** [comment]
what about adding a script with sudo permissions for terminating miner and calling this script from m2m? 
I see that in 1.50 sometimes mining stops in dual mode even when miner is running. In that case restarting miner would be the only way.

**Comment by bds89** [comment]
In version 1.6.1 added the ability to stop, start and restart the miner by publishing Stop/Start/Restart messages in `your_topic/to_miner/miner_state`. The current state of the miner can be geted in `your_topic/from_miner/miner_state`. To control the process of the miner, it is necessary that `miner2mqtt` itself starts the miner with a command from `COMMAND`. Also, since version 1.6, the `TrexAPI`, `lolAPI` parameters have been replaced with the `API` general parameter, the `danila_command`, `lol_command` parameters have been replaced with the `COMMAND` general parameter. To change the state of the miner from `miner2android`, you need to click on the farm icon in the upper left corner. Tested on Linux only.

**Comment by sheminasalam** [comment]
I have a small doubt with

> To control the process of the miner, it is necessary that `miner2mqtt` itself starts the miner with a command from `COMMAND`

So to control the miner with m2m, I have to first start m2m and then start mining by sending a mqtt message like ```your_topic/to_miner/start``` . Is this how it should be done?

**Comment by sheminasalam** [comment]
Great man....thanks.. appreciate the good work.
Hope you can make the android app available outside the local network using some tunneling service or so.

**Comment by sheminasalam** [comment]
Can this be used to start or stop Trex miner? It works very well with lol miner but I am not able to use it with Trex.

**Comment by bds89** [comment]
The script gets the pid of the miner process when it starts. In theory, it should work for any miner. I can't test this yet and find a bug, because of the low rate and high temperature, I temporarily stopped my rig)
